# Generated by Django 4.2.7 on 2026-04-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_gender_studentapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_left',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('transferred', 'Transferred'), ('graduated', 'Graduated')], default='active', max_length=20),
        ),
    ]
