# Generated by Django 4.2.7 on 2026-04-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_user'),
        ('students', '0005_student_user'),
    ]

    operations = [
    ]
