# Generated by Django 4.2.7 on 2026-04-25 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_merge_0002_student_user_0005_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(help_text='Label shown on form', max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('phone', 'Phone'), ('textarea', 'Text Area'), ('date', 'Date'), ('select', 'Dropdown'), ('checkbox', 'Checkbox'), ('file', 'File Upload')], default='text', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('placeholder', models.CharField(blank=True, max_length=150)),
                ('choices', models.TextField(blank=True, help_text='For dropdown: comma-separated values')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='students.studentapplication')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.admissionformfield')),
            ],
            options={
                'unique_together': {('application', 'field')},
            },
        ),
    ]
