# Generated by Django 4.2.7 on 2026-04-28 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0007_admissionformfield_admissionformresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view_own_profile', 'View Own Profile'), ('view_own_results', 'View Own Results'), ('download_report_card', 'Download Report Card'), ('view_own_fees', 'View School Fees'), ('view_class_timetable', 'View Class Timetable'), ('view_class_announcements', 'View Class Announcements'), ('submit_assignments', 'Submit Assignments'), ('view_attendance', 'View Own Attendance'), ('contact_teacher', 'Contact Teachers'), ('access_portal', 'Access Student Portal')], max_length=50)),
                ('is_granted', models.BooleanField(default=True, help_text='Whether this permission is granted to the student')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this permission')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_student_permissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Student Permissions',
                'unique_together': {('student', 'permission')},
            },
        ),
    ]
