# Generated by Django 4.2.7 on 2026-05-07 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpermission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='students.student'),
        ),
    ]
