# Generated by Django 5.1.3 on 2026-08-31 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0025_tenant_schoolsettings_tenant'),
        ('students', '0010_student_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='settingsapp.tenant'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('tenant', 'admission_no')},
        ),
    ]
