# Generated by Django 5.1.3 on 2026-09-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_studentapplication_tenant_alter_student_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to='students/passports/'),
        ),
    ]
