# Generated by Django 5.1.3 on 2026-09-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='photo',
            field=models.ImageField(blank=True, upload_to='students/passports/'),
        ),
    ]
