# Generated by Django 4.2.7 on 2026-05-21 20:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_classes', '0004_add_scheme_week_approval_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude used for GPS validation.', max_digits=9, null=True)),
                ('school_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude used for GPS validation.', max_digits=9, null=True)),
                ('allowed_radius_meters', models.PositiveIntegerField(default=200, help_text='Maximum distance from school for valid clock in/out.')),
                ('normal_clock_in_time', models.TimeField(default=datetime.time(8, 0), help_text='Latest time considered on-time for clock in.')),
                ('late_after_time', models.TimeField(default=datetime.time(8, 30), help_text='Time after which clock-in is marked late.')),
                ('earliest_clock_out_time', models.TimeField(default=datetime.time(15, 0), help_text='Earliest time a teacher may clock out.')),
                ('enable_gps_verification', models.BooleanField(default=True, help_text='Require GPS verification for attendance actions.')),
                ('enable_clock_out', models.BooleanField(default=True, help_text='Allow staff to clock out after clock in.')),
                ('enable_offline_sync', models.BooleanField(default=True, help_text='Allow offline attendance records to sync automatically later.')),
                ('active', models.BooleanField(default=True, help_text='Only one active configuration is used by the system.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Setting',
                'verbose_name_plural': 'Attendance Settings',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('clock_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_in_status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], default='present', max_length=10)),
                ('synced', models.BooleanField(default=False)),
                ('sync_time', models.DateTimeField(blank=True, null=True)),
                ('device_info', models.TextField(blank=True)),
                ('offline_record', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance', to='school_classes.teacher')),
            ],
            options={
                'ordering': ['-date', '-clock_in'],
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
