# Generated by Django 4.2.7 on 2026-05-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffattendance",
            name="is_suspicious",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staffattendance",
            name="offline_sync_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="staffattendance",
            name="work_duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
