# Generated by Django 5.1.3 on 2026-07-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_attendance', '0002_staffattendance_is_suspicious_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_student_attendance', models.BooleanField(default=True, help_text='Enable student attendance features in the portal.')),
                ('require_daily_checkin', models.BooleanField(default=False, help_text='Require students to check in daily via the portal/mobile app.')),
                ('allow_parent_reason_submission', models.BooleanField(default=True, help_text='Allow parents/guardians to submit reasons for absence.')),
                ('absence_threshold_warning', models.PositiveIntegerField(default=5, help_text='Number of absent days in a term before warning is triggered.')),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Attendance Setting',
                'verbose_name_plural': 'Student Attendance Settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
