# Generated by Django 5.1.3 on 2026-09-02 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0025_tenant_schoolsettings_tenant'),
        ('staff_attendance', '0003_studentattendancesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesettings',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant'),
        ),
        migrations.AddField(
            model_name='studentattendancesettings',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant'),
        ),
    ]
