# Generated by Django 4.2.7 on 2026-05-19 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0005_make_required'),
        ('students', '0010_student_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='psychomotor.traitcategory')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTraitRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=3)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychomotor.trait')),
            ],
            options={
                'unique_together': {('student', 'trait', 'exam')},
            },
        ),
    ]
