# Generated by Django 4.2.7 on 2026-04-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title displayed on the website', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly unique identifier (auto-generated from title)', unique=True)),
                ('content', models.TextField(blank=True, help_text='Main content for the page (optional)', null=True)),
                ('template', models.CharField(default='default.html', help_text='Template file to render (relative to pages/ directory)', max_length=100)),
                ('page_type', models.CharField(choices=[('normal', 'Normal Page'), ('messages', 'Messages Page'), ('news', 'News Page')], default='normal', help_text='Type of page - determines how content is fetched and displayed', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible JSON field for future extensions and component data', null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Only published pages are visible on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['-created_at'],
            },
        ),
    ]
