# Generated by Django 4.2.7 on 2026-04-22 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or heading for this content section', max_length=255)),
                ('body', models.TextField(help_text='Main content body (supports HTML in future)')),
                ('image', models.ImageField(blank=True, help_text='Optional image for this content section', null=True, upload_to='page_contents/')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Flexible JSON field for future extensions (e.g., lessons, objectives)', null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Only published content is visible to users')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this content', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_contents_created', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(help_text='The page this content belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='pages.page')),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Contents',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['page', 'is_published', 'order'], name='pages_pagec_page_id_a1064b_idx')],
            },
        ),
    ]
