# Generated by Django 4.2.7 on 2026-04-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_page_show_on_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontent",
            name="show_on_homepage",
            field=models.BooleanField(
                default=False, help_text="Display this page on homepage"
            ),
        ),
    ]
