# Generated by Django 4.2.7 on 2026-04-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_pagecontent_show_on_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="url_prefix",
            field=models.CharField(
                blank=True,
                help_text="Optional prefix like 'results', 'classes', 'announcements'",
                max_length=100,
                null=True,
            ),
        ),
    ]
