# Generated by Django 4.2.7 on 2026-04-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_page_url_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="show_in_navigation",
            field=models.BooleanField(
                default=False,
                help_text="Show this page as a link in its section (classes, results, etc.)",
            ),
        ),
    ]
