# Generated by Django 4.2.7 on 2026-04-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_page_show_in_navigation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="url_prefix",
        ),
        migrations.AddField(
            model_name="page",
            name="prefix",
            field=models.CharField(
                blank=True,
                help_text="Optional prefix like 'results', 'classes', 'announcements'",
                max_length=100,
                null=True,
            ),
        ),
    ]
