# Generated by Django 5.2.13 on 2026-04-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_remove_page_url_prefix_page_prefix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="prefix",
        ),
        migrations.AddField(
            model_name="page",
            name="theme",
            field=models.CharField(
                blank=True,
                default="default",
                help_text="Theme class for styling (e.g., 'default', 'dark', 'school')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="url_prefix",
            field=models.CharField(
                blank=True,
                help_text="Optional prefix like 'results', 'classes', 'announcements'",
                max_length=100,
                null=True,
            ),
        ),
    ]
