# Generated by Django 4.2.7 on 2026-04-19 20:52

from django.db import migrations


def create_initial_data(apps, schema_editor):
    """Create initial terms, exam types, and subjects"""
    Term = apps.get_model('exams', 'Term')
    ExamType = apps.get_model('exams', 'ExamType')
    Subject = apps.get_model('exams', 'Subject')

    # Create terms
    Term.objects.get_or_create(
        name='first',
        defaults={
            'display_name': 'First Term',
            'academic_year': '2023/2024',
            'is_active': True
        }
    )
    Term.objects.get_or_create(
        name='second',
        defaults={
            'display_name': 'Second Term',
            'academic_year': '2023/2024',
            'is_active': False
        }
    )
    Term.objects.get_or_create(
        name='third',
        defaults={
            'display_name': 'Third Term',
            'academic_year': '2023/2024',
            'is_active': False
        }
    )

    # Create exam types
    ExamType.objects.get_or_create(
        name='Test',
        defaults={
            'assessment_type': 'test',
            'max_score': 40.00,
            'weight_percentage': 40.00,
            'description': 'Class test or continuous assessment',
            'is_active': True
        }
    )
    ExamType.objects.get_or_create(
        name='Exam',
        defaults={
            'assessment_type': 'exam',
            'max_score': 60.00,
            'weight_percentage': 60.00,
            'description': 'Final examination',
            'is_active': True
        }
    )

    # Create common subjects
    subjects_data = [
        ('Mathematics', 'MATH'),
        ('English Language', 'ENG'),
        ('Basic Science', 'BSC'),
        ('Social Studies', 'SOS'),
        ('Civic Education', 'CIV'),
        ('Computer Studies', 'COM'),
        ('Home Economics', 'HEC'),
        ('Agricultural Science', 'AGS'),
        ('Physical Education', 'PED'),
        ('Islamic Studies', 'ISR'),
        ('Christian Religious Studies', 'CRS'),
        ('Hausa Language', 'HAU'),
        ('Arabic Language', 'ARB'),
        ('French Language', 'FRE'),
        ('Fine Arts', 'ART'),
        ('Music', 'MUS'),
    ]

    for name, code in subjects_data:
        Subject.objects.get_or_create(
            name=name,
            defaults={
                'code': code,
                'is_active': True
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examtype_term_exam_is_active_exam_school_class_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
