# Generated by Django 4.2.7 on 2026-04-19 20:56

from django.db import migrations


def populate_exam_defaults(apps, schema_editor):
    """Populate default values for existing Exam records"""
    Exam = apps.get_model('exams', 'Exam')
    Term = apps.get_model('exams', 'Term')
    ExamType = apps.get_model('exams', 'ExamType')
    SchoolClasses = apps.get_model('school_classes', 'SchoolClasses')

    # Get default term, exam type, and class
    first_term = Term.objects.filter(name='first').first()
    exam_type = ExamType.objects.filter(name='Exam').first()
    default_class = SchoolClasses.objects.first()  # Get first available class

    if first_term and exam_type and default_class:
        # Update existing exams with null values
        Exam.objects.filter(term__isnull=True).update(term=first_term)
        Exam.objects.filter(exam_type__isnull=True).update(exam_type=exam_type)
        Exam.objects.filter(school_class__isnull=True).update(school_class=default_class)


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_initial_data'),
    ]

    operations = [
        migrations.RunPython(populate_exam_defaults),
    ]
