# Generated by Django 4.2.7 on 2026-04-19 21:01

from django.db import migrations


def fix_null_school_class(apps, schema_editor):
    """Fix remaining null school_class values in Exam records"""
    Exam = apps.get_model('exams', 'Exam')
    SchoolClasses = apps.get_model('school_classes', 'SchoolClasses')

    # Get first available class
    default_class = SchoolClasses.objects.first()
    if default_class:
        Exam.objects.filter(school_class__isnull=True).update(school_class=default_class)


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_populate_defaults'),
    ]

    operations = [
        migrations.RunPython(fix_null_school_class),
    ]
