# Generated by Django 4.2.7 on 2026-05-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_term_name_alter_term_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
