# Generated by Django 4.2.7 on 2026-06-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_exampaper_examsection_question_questionoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='resource_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='examsection',
            name='section_type',
            field=models.CharField(choices=[('objective', 'Objective'), ('theory', 'Theory'), ('german', 'German Questions'), ('other', 'Custom / Optional')], default='theory', max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='subnumbering_style',
            field=models.CharField(blank=True, choices=[('', 'No sub-question numbering'), ('parent_alpha', '1(a), 1(b), 1(c)'), ('roman', 'i, ii, iii'), ('alpha', 'a, b, c'), ('custom', 'Custom')], default='', max_length=20),
        ),
    ]
