# Generated by Django 4.2.7 on 2026-06-09 08:35

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0009_question_resource_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Admin notes on approval/rejection'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_explanation',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Explanation shown to students after submission'),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='instructions',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Instructions for students'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=ckeditor.fields.RichTextField(help_text='Question text with support for images, diagrams, tables, and math'),
        ),
        migrations.AlterField(
            model_name='question',
            name='resource_notes',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Additional supplementary resources and notes'),
        ),
        migrations.AlterField(
            model_name='question',
            name='teacher_guide',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Teacher guide with suggested answers, diagrams, and solutions'),
        ),
    ]
