# Generated by Django 5.1.3 on 2026-07-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_exampaper_approval_notes_exampaper_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='next_term_begins_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
