# Generated by Django 5.1.3 on 2026-09-01 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_alter_term_unique_together_subject_tenant_and_more'),
        ('school_classes', '0005_schoolclasses_tenant_alter_schoolclasses_class_name_and_more'),
        ('settingsapp', '0025_tenant_schoolsettings_tenant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant'),
        ),
        migrations.AddField(
            model_name='exam',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant'),
        ),
        migrations.AddField(
            model_name='examtype',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant'),
        ),
        migrations.AlterField(
            model_name='term',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('tenant', 'school_class', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('tenant', 'term', 'school_class', 'exam_type')},
        ),
        migrations.AlterUniqueTogether(
            name='examtype',
            unique_together={('tenant', 'name')},
        ),
    ]
