# Generated by Django 5.1.3 on 2026-07-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_create_portal_thread_and_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='portal_attachments/'),
        ),
        migrations.AddField(
            model_name='portalmessage',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=12),
        ),
    ]
