# Generated by Django 5.1.3 on 2026-08-01 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_portalmessage_attachment_portalmessage_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portalthread',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='portalthread',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='portal_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='portalthread',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_thread', to=settings.AUTH_USER_MODEL),
        ),
    ]
