# Generated by Django 5.1.3 on 2026-08-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_portalthread_name_portalthread_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalthread',
            name='thread_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('group', 'Group'), ('class', 'Class')], default='group', help_text='Explicit type of portal conversation.', max_length=10),
        ),
    ]
