# Generated by Django 5.1.3 on 2026-09-01 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_portalthread_backfill_thread_types'),
        ('settingsapp', '0025_tenant_schoolsettings_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant'),
        ),
        migrations.AddField(
            model_name='portalthread',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant'),
        ),
    ]
