# Generated by Django 4.2.7 on 2026-04-19 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_classes', '0003_teacher_schemeofwork_teacherpermission_schemeweek_and_more'),
        ('payroll', '0002_payrolldashboard_salarycomponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_staff', to='school_classes.teacher'),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='payroll.staff'),
        ),
        migrations.AddField(
            model_name='payrolldashboard',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.staff'),
        ),
        migrations.AlterUniqueTogether(
            name='payrolldashboard',
            unique_together={('staff', 'month')},
        ),
    ]
