# Generated by Django 5.1.3 on 2026-07-11 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_term_next_term_begins_date'),
        ('payroll', '0003_staff_teacher_salarycomponent_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinvoice',
            name='academic_session',
            field=models.CharField(blank=True, help_text='e.g., 2023/2024', max_length=20),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='exams.term'),
        ),
    ]
