# Generated by Django 5.1.3 on 2026-09-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_staff_user'),
        ('school_classes', '0008_schemeofwork_completion_acknowledged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfee',
            name='school_classes',
            field=models.ManyToManyField(blank=True, help_text='Students in these classes inherit this fee when creating an invoice.', related_name='school_fees', to='school_classes.schoolclasses'),
        ),
    ]
