# Generated by Django 5.1.3 on 2026-09-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_studentpayment_allocations_studentpayment_invoices_studentpayment_remaining_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='wallet_applied',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount taken from the student wallet for this payment.', max_digits=12),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='wallet_used',
            field=models.BooleanField(default=False, help_text='Whether any prior student wallet balance was consumed for this payment.'),
        ),
    ]
