# Generated by Django 5.1.3 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_studentpayment_wallet_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='wallet_refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cash returned to the student from their wallet balance.', max_digits=12),
        ),
    ]
