# Generated by Django 5.1.3 on 2026-07-18 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        ('settingsapp', '0017_alter_galleryimage_image_alter_galleryimage_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Announcement Category',
                'verbose_name_plural': 'Announcement Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='excerpt',
            field=models.CharField(blank=True, help_text='Short summary shown in lists', max_length=500),
        ),
        migrations.AddField(
            model_name='announcement',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/images/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='galleries',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='settingsapp.galleryimage'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/videos/thumbnails/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional video URL (YouTube embed or mp4 link)', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='announcements.announcementcategory'),
        ),
    ]
