# Generated by Django 5.1.3 on 2026-07-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcementcategory_announcement_excerpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='title_alignment',
            field=models.CharField(choices=[('start', 'Left'), ('center', 'Center'), ('end', 'Right')], default='start', help_text='Title alignment on the announcement page', max_length=10),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='large', help_text='Title size shown on the announcement page', max_length=10),
        ),
    ]
