# Generated by Django 5.1.3 on 2026-09-01 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_announcement_tenant'),
        ('settingsapp', '0025_tenant_schoolsettings_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementcategory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant'),
        ),
        migrations.AlterField(
            model_name='announcementcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='announcementcategory',
            unique_together={('tenant', 'name')},
        ),
    ]
