# Generated by Django 4.2.7 on 2026-05-22 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_classes', '0004_add_scheme_week_approval_fields'),
        ('exams', '0007_term_end_date_term_start_date'),
        ('cbt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtexam',
            name='allow_navigation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='allow_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='balance_by_difficulty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='balance_by_topic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='one_at_a_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='question_mode',
            field=models.CharField(choices=[('manual', 'Manual Selection'), ('random', 'Random Selection')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='randomize_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='randomize_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='show_corrections',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='show_instant_results',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='total_questions_to_display',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cbtquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cbtquestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=16),
        ),
        migrations.AddField(
            model_name='cbtquestion',
            name='topic',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_question_banks', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbt_question_banks', to='school_classes.schoolclasses')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cbt_question_banks', to='exams.subject')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbt_question_banks', to='exams.term')),
            ],
            options={
                'verbose_name': 'Question Bank',
                'verbose_name_plural': 'Question Banks',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='cbt.questionbank'),
        ),
        migrations.AddField(
            model_name='cbtquestion',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='cbt.questionbank'),
        ),
        migrations.CreateModel(
            name='StudentAttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('randomized_position', models.PositiveIntegerField()),
                ('randomized_choice_order', models.TextField(blank=True)),
                ('is_answered', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='cbt.cbtstudentattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.cbtquestion')),
            ],
            options={
                'ordering': ['randomized_position'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
