# Generated by Django 4.2.7 on 2026-05-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0002_cbtexam_allow_navigation_cbtexam_allow_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtanswer',
            name='selected_choices',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cbtquestion',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='cbt/question_images/'),
        ),
        migrations.AlterField(
            model_name='cbtquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('multiple', 'Multiple Select'), ('true_false', 'True / False'), ('short_answer', 'Short Answer')], default='mcq', max_length=32),
        ),
    ]
