# Generated by Django 4.2.7 on 2026-05-22 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0003_cbtanswer_selected_choices_cbtquestion_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBTAttemptIntegrityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_events', to='cbt.cbtstudentattempt')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
