# Generated by Django 4.2.7 on 2026-05-22 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbt", "0003_cbtanswer_selected_choices_and_more"),
        ("cbt", "0003_cbtanswer_selected_choices_cbtquestion_image_and_more"),
    ]

    operations = []
