# Generated by Django 4.2.7 on 2026-05-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbt", "0004_cbtattemptintegrityevent"),
        ("cbt", "0004_merge_20260522_0353"),
    ]

    operations = []
