# Generated by Django 4.2.7 on 2026-05-23 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cbt", "0005_merge_20260522_1358"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRequestMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("generate_ai_questions", "Generate AI Questions"),
                            ("generate_ss1_questions", "Generate SS1 Questions"),
                        ],
                        default="generate_ai_questions",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("quota_failure", "Quota / Rate Limit"),
                            ("throttled", "Throttled"),
                        ],
                        default="failure",
                        max_length=32,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=128)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("token_usage", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_request_metrics",
                        to="cbt.cbtexam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_request_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Request Metric",
                "verbose_name_plural": "AI Request Metrics",
                "ordering": ["-created_at"],
            },
        ),
    ]
