# Generated by Django 5.1.3 on 2026-08-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0006_airequestmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtquestion',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cbtquestion',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=250),
        ),
        migrations.AddField(
            model_name='cbtquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
