# Generated by Django 5.1.3 on 2026-09-12 10:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0013_alter_classsubject_unique_together_and_more'),
        ('school_classes', '0008_schemeofwork_completion_acknowledged_and_more'),
        ('settingsapp', '0029_tenant_access_mode_alter_tenant_hostname'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=15)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_short_day', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimetableTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='timetable.timetabletemplate')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_templates', to='school_classes.schoolclasses')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_templates', to='exams.term')),
            ],
            options={
                'ordering': ['-term__academic_year', 'term__name', 'school_class__class_name'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('slot_type', models.CharField(choices=[('period', 'Teaching Period'), ('break', 'Break'), ('salah', 'Salah / Prayer'), ('assembly', 'Assembly')], default='period', max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='timetable.timetabletemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=120)),
                ('class_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='exams.classsubject')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.timetableday')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='school_classes.teacher')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.timetableslot')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.timetabletemplate')),
            ],
        ),
        migrations.AddField(
            model_name='timetableday',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='timetable.timetabletemplate'),
        ),
        migrations.AddConstraint(
            model_name='timetabletemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'term', 'school_class'), name='unique_timetable_per_term_class'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(fields=('timetable', 'order'), name='unique_timetable_slot_order'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('timetable', 'day', 'slot'), name='unique_timetable_entry'),
        ),
        migrations.AddConstraint(
            model_name='timetableday',
            constraint=models.UniqueConstraint(fields=('timetable', 'day'), name='unique_timetable_day'),
        ),
    ]
