# Generated by Django 4.2.7 on 2026-04-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='accent_color',
            field=models.CharField(default='#ffc107', help_text='Accent color for buttons and highlights (hex format)', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='background_color',
            field=models.CharField(default='#f5f5ff', help_text='Background color (hex format)', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='primary_color',
            field=models.CharField(default='#4b2e83', help_text='Primary color for header and accents (hex format)', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='secondary_color',
            field=models.CharField(default='#7f5af0', help_text='Secondary color for gradients (hex format)', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='text_color',
            field=models.CharField(default='#202040', help_text='Main text color (hex format)', max_length=7),
        ),
    ]
