# Generated by Django 4.2.7 on 2026-04-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0002_schoolsettings_accent_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('home', 'Home Page'), ('classes', 'Classes Page'), ('results', 'Results Page'), ('settings', 'Settings Page'), ('students', 'Students Page'), ('attendance', 'Attendance Page'), ('exams', 'Exams Page'), ('psychomotor', 'Psychomotor Page'), ('payroll', 'Payroll Page')], help_text='Select which page this theme applies to', max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable or disable this page theme')),
                ('primary_color', models.CharField(default='#4b2e83', help_text='Primary color for header and accents (hex format)', max_length=7)),
                ('secondary_color', models.CharField(default='#7f5af0', help_text='Secondary color for gradients (hex format)', max_length=7)),
                ('accent_color', models.CharField(default='#ffc107', help_text='Accent color for buttons and highlights (hex format)', max_length=7)),
                ('background_color', models.CharField(default='#f5f5ff', help_text='Background color (hex format)', max_length=7)),
                ('text_color', models.CharField(default='#202040', help_text='Main text color (hex format)', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Page Themes',
                'ordering': ['page_name'],
            },
        ),
    ]
