# Generated by Django 4.2.7 on 2026-04-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0003_pagetheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetheme',
            name='page_display_name',
            field=models.CharField(blank=True, help_text="Display name for this page (optional, e.g., 'Home Page', 'Custom Reports')", max_length=100),
        ),
        migrations.AddField(
            model_name='pagetheme',
            name='url_pattern',
            field=models.CharField(blank=True, help_text="URL path to match (e.g., '/classes/', '/announcements/'). Leave blank for automatic detection.", max_length=100),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='page_name',
            field=models.CharField(help_text="Enter page name (e.g., 'home', 'classes', 'announcements'). Use lowercase with underscores for spaces.", max_length=50, unique=True),
        ),
    ]
