# Generated by Django 4.2.7 on 2026-04-16 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0004_pagetheme_page_display_name_pagetheme_url_pattern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload gallery image', upload_to='gallery/')),
                ('title', models.CharField(blank=True, help_text='Image title or caption (optional)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Image description (optional)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='settingsapp.schoolsettings')),
            ],
            options={
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
