# Generated by Django 4.2.7 on 2026-04-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0005_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetheme',
            name='heading_text_color',
            field=models.CharField(default='#2a2a2a', help_text='Heading text color (hex format)', max_length=7),
        ),
        migrations.AddField(
            model_name='pagetheme',
            name='icon_plate_color',
            field=models.CharField(default='#e8e0ff', help_text='Icon plate/background color (hex format)', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='heading_text_color',
            field=models.CharField(default='#2a2a2a', help_text='Heading text color (hex format)', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='icon_plate_color',
            field=models.CharField(default='#e8e0ff', help_text='Icon plate/background color (hex format)', max_length=7),
        ),
    ]
