# Generated by Django 4.2.7 on 2026-04-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0006_pagetheme_heading_text_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetheme',
            name='header_heading_color',
            field=models.CharField(default='#ffffff', help_text='Header heading/school name color (hex format)', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='header_heading_color',
            field=models.CharField(default='#ffffff', help_text='Header heading/school name color (hex format)', max_length=7),
        ),
    ]
