# Generated by Django 4.2.7 on 2026-04-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0007_pagetheme_header_heading_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetheme',
            name='icon_color',
            field=models.CharField(default='#4b2e83', help_text='Icon/emoji color (hex format)', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='icon_color',
            field=models.CharField(default='#4b2e83', help_text='Icon/emoji color (hex format)', max_length=7),
        ),
    ]
