# Generated by Django 4.2.7 on 2026-04-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0008_pagetheme_icon_color_schoolsettings_icon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_video_description',
            field=models.TextField(blank=True, default='Replace this placeholder with your school introduction video. Edit the template at templates/home.html to add your video embed code.', help_text='Description text for the video placeholder on homepage'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_welcome_text',
            field=models.TextField(blank=True, default='Welcome to the official digital platform of DAARUL BAYAAN ISLAMIC SCHOOL — a place designed to make learning, communication, and school management easier, faster, and more accessible for everyone. We provide a balanced education that combines Western and Islamic studies, including modern fields such as STEM and Robotics.', help_text='Welcome text displayed on the homepage for visitors'),
        ),
    ]
