# Generated by Django 4.2.7 on 2026-04-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingsapp", "0009_schoolsettings_homepage_video_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Upload video (optional)",
                null=True,
                upload_to="gallery/videos/",
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload image (optional)",
                null=True,
                upload_to="gallery/images/",
            ),
        ),
    ]
