# Generated by Django 4.2.7 on 2026-04-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingsapp", "0010_galleryimage_video_alter_galleryimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="homepage_video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="homepage_video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
