# Generated by Django 4.2.7 on 2026-04-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settingsapp", "0011_schoolsettings_homepage_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="homepage_video_url",
            field=models.URLField(
                blank=True,
                help_text="Paste YouTube embed link (https://www.youtube.com/embed/...)",
                null=True,
            ),
        ),
    ]
