# Generated by Django 4.2.7 on 2026-04-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0012_galleryimage_homepage_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='account_creation_email_subject',
            field=models.CharField(default='New Account Created - {school_name}', help_text='Email subject for account creation. Use {school_name} as placeholder', max_length=200),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='admin_email',
            field=models.EmailField(default='daarulbayaanis@gmail.com', help_text='Primary email address for receiving notifications (account creation, contact messages, etc.)', max_length=254),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='admin_email_cc',
            field=models.CharField(blank=True, help_text='Additional email addresses to CC on notifications (comma-separated)', max_length=500),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='application_email_subject',
            field=models.CharField(default='New Application Received - {school_name}', help_text='Email subject for applications. Use {school_name} as placeholder', max_length=200),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='contact_message_email_subject',
            field=models.CharField(default='New Contact Message - {school_name}', help_text='Email subject for contact messages. Use {school_name} as placeholder', max_length=200),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='send_account_creation_email',
            field=models.BooleanField(default=True, help_text='Send email notification when new accounts are created'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='send_application_email',
            field=models.BooleanField(default=True, help_text='Send email notification when applications/forms are submitted'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='send_contact_message_email',
            field=models.BooleanField(default=True, help_text='Send email notification when contact form messages are submitted'),
        ),
    ]
