# Generated by Django 4.2.7 on 2026-05-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0013_schoolsettings_account_creation_email_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='school_address',
            field=models.TextField(blank=True, default='123 Main Street, City, Country', help_text='School physical address displayed in header and documents', null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='school_email',
            field=models.EmailField(blank=True, default='info@daarulbayaan.edu', help_text='School general contact email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='school_phone',
            field=models.CharField(blank=True, default='+234 (0) 123 456 7890', help_text='School contact phone number', max_length=20, null=True),
        ),
    ]
