# Generated by Django 4.2.7 on 2026-05-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0014_schoolsettings_school_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='footer_copyright_link',
            field=models.URLField(blank=True, help_text='Optional link for copyright (e.g., privacy policy URL)', null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='footer_copyright_text',
            field=models.CharField(blank=True, default='© 2026 Daarul Bayaan Islamic School. All Rights Reserved.', help_text='Copyright text displayed in footer', max_length=500),
        ),
    ]
