# Generated by Django 4.2.7 on 2026-06-21 12:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settingsapp", "0015_schoolsettings_footer_copyright_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload image (optional)",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="video",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload video (optional)",
                max_length=255,
                null=True,
                verbose_name="video",
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="homepage_video",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="videos"
            ),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="logo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
