# Generated by Django 5.1.3 on 2026-06-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0016_alter_galleryimage_image_alter_galleryimage_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image (optional)', null=True, upload_to='gallery/images/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='video',
            field=models.FileField(blank=True, help_text='Upload video (optional)', null=True, upload_to='gallery/videos/'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='homepage_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
