# Generated by Django 5.1.3 on 2026-07-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0017_alter_galleryimage_image_alter_galleryimage_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_hero_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable the modern homepage hero section for visitors'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_hero_show_announcements',
            field=models.BooleanField(default=True, help_text='Show announcement preview inside the homepage hero'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_hero_show_counters',
            field=models.BooleanField(default=True, help_text='Display counts for announcements and gallery highlights in the homepage hero'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_hero_slide_duration',
            field=models.PositiveIntegerField(default=6500, help_text='Hero background slide duration in milliseconds'),
        ),
    ]
