# Generated by Django 5.1.3 on 2026-07-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0018_schoolsettings_homepage_hero_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='usage',
            field=models.CharField(choices=[('gallery', 'Gallery'), ('hero', 'Hero (Homepage)'), ('portal_video', 'Portal Video')], default='gallery', help_text="How this media item is used on the site. 'Hero' images appear in the homepage hero.", max_length=20),
        ),
    ]
