# Generated by Django 5.1.3 on 2026-07-21 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0019_galleryimage_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='enable_auto_slide',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='enable_hero_overlay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='enable_hero_text_animation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='hero_animation_speed',
            field=models.PositiveIntegerField(default=900, help_text='Animation speed in milliseconds for text transitions'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='hero_height',
            field=models.CharField(blank=True, default='80vh', help_text='CSS height value for the hero (e.g., 80vh, 600px)', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='hero_overlay_opacity',
            field=models.PositiveSmallIntegerField(default=50, help_text='Overlay opacity percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='hero_text_position',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', help_text='Position of hero text', max_length=10),
        ),
        migrations.CreateModel(
            name='HeroButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_buttons', to='settingsapp.schoolsettings')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('button_text', models.CharField(blank=True, max_length=120)),
                ('button_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('animation_type', models.CharField(default='fade', help_text='fade|typewriter', max_length=32)),
                ('display_seconds', models.PositiveIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_texts', to='settingsapp.schoolsettings')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
