# Generated by Django 5.1.3 on 2026-07-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0020_schoolsettings_enable_auto_slide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_gallery_description',
            field=models.TextField(blank=True, default='Browse highlights from the portal and explore the types of information available.', help_text='Description for the gallery section'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_gallery_title',
            field=models.CharField(blank=True, default='Portal Gallery', help_text='Title for the gallery section', max_length=120),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_help_text',
            field=models.TextField(blank=True, default='If you experience any difficulty accessing your account or navigating the portal, please contact the school administration for assistance.', help_text='Body text for the help section'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_help_title',
            field=models.CharField(blank=True, default='Need Help?', help_text='Title for the help section', max_length=120),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_hero_announcements_label',
            field=models.CharField(blank=True, default='Latest Announcement', help_text='Label shown above the announcement preview in the hero', max_length=80),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_hero_eyebrow',
            field=models.CharField(blank=True, default='Welcome to', help_text='Short label above the hero heading', max_length=80),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_hero_intro',
            field=models.TextField(blank=True, default='A nurturing and modern learning environment for students, families, and staff.', help_text='Supporting copy shown beneath the hero title'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_hero_primary_cta_label',
            field=models.CharField(blank=True, default='Apply for Admission', help_text='Primary CTA label in the hero', max_length=60),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_hero_secondary_cta_label',
            field=models.CharField(blank=True, default='Contact Us', help_text='Secondary CTA label in the hero', max_length=60),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_hero_stat_announcements_label',
            field=models.CharField(blank=True, default='Announcements', help_text='Label for the announcements hero stat card', max_length=40),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_hero_stat_gallery_label',
            field=models.CharField(blank=True, default='Gallery', help_text='Label for the gallery hero stat card', max_length=40),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_hero_stat_students_label',
            field=models.CharField(blank=True, default='Students', help_text='Label for the students hero stat card', max_length=40),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_hero_stat_teachers_label',
            field=models.CharField(blank=True, default='Teachers', help_text='Label for the teachers hero stat card', max_length=40),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_hero_tertiary_cta_label',
            field=models.CharField(blank=True, default='View Gallery', help_text='Tertiary CTA label in the hero', max_length=60),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_hero_title',
            field=models.CharField(blank=True, default='A premium school experience rooted in excellence', help_text='Main heading displayed in the homepage hero', max_length=160),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_important_notice_text',
            field=models.TextField(blank=True, default='Your login details are personal and should not be shared with anyone. Keep your credentials safe to protect your academic information.', help_text='Body text for the important notice section'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_important_notice_title',
            field=models.CharField(blank=True, default='Important Notice', help_text='Title for the important notice section', max_length=120),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_overview_card_1_description',
            field=models.TextField(blank=True, default='View your results, grades, and progress reports from one secure location.', help_text='Description for the first overview card'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_overview_card_1_title',
            field=models.CharField(blank=True, default='Access academic records', help_text='Title for the first overview card', max_length=120),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_overview_card_2_description',
            field=models.TextField(blank=True, default='Check timetables, subject details, and classroom assignments at a glance.', help_text='Description for the second overview card'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_overview_card_2_title',
            field=models.CharField(blank=True, default='View class schedules', help_text='Title for the second overview card', max_length=120),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_overview_card_3_description',
            field=models.TextField(blank=True, default='Stay informed with announcements, news, and important school events.', help_text='Description for the third overview card'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_overview_card_3_title',
            field=models.CharField(blank=True, default='Receive school updates', help_text='Title for the third overview card', max_length=120),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_overview_card_4_description',
            field=models.TextField(blank=True, default="Message teachers and school management through the portal's secure channels.", help_text='Description for the fourth overview card'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_overview_card_4_title',
            field=models.CharField(blank=True, default='Communicate easily', help_text='Title for the fourth overview card', max_length=120),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_overview_card_5_description',
            field=models.TextField(blank=True, default='Update your account information and keep your profile current.', help_text='Description for the fifth overview card'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_overview_card_5_title',
            field=models.CharField(blank=True, default='Manage your profile', help_text='Title for the fifth overview card', max_length=120),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_overview_intro',
            field=models.TextField(blank=True, default='Explore a secure digital experience designed to keep students, families, and staff connected.', help_text='Intro paragraph shown above the overview cards'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_overview_title',
            field=models.CharField(blank=True, default='What You Can Do on This Portal', help_text='Heading for the overview cards section', max_length=140),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_updates_empty_text',
            field=models.CharField(blank=True, default='No updates available yet.', help_text='Message shown when no updates are available', max_length=200),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='homepage_updates_title',
            field=models.CharField(blank=True, default='Latest Updates', help_text='Title shown for the latest updates section', max_length=120),
        ),
    ]
