# Generated by Django 5.1.3 on 2026-07-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0021_schoolsettings_homepage_gallery_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herotext',
            name='animation_styles',
            field=models.CharField(blank=True, default='fade,slide', help_text='Comma-separated animation styles to rotate through, e.g. fade,slide,typing', max_length=200),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='hero_button_background_color',
            field=models.CharField(blank=True, default='#4b2e83', help_text='Background color for hero CTA buttons', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='hero_button_border_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Border color for hero CTA buttons', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='hero_button_font_size',
            field=models.CharField(blank=True, default='0.82rem', help_text='CSS font size for hero buttons', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='hero_button_hover_background_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Hover background color for hero CTA buttons', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='hero_button_hover_text_color',
            field=models.CharField(blank=True, default='#4b2e83', help_text='Hover text color for hero CTA buttons', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='hero_button_text_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Text color for hero CTA buttons', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='hero_intro_font_size',
            field=models.CharField(blank=True, default='clamp(0.95rem, 1.35vw, 1.05rem)', help_text='CSS font size for the hero intro / supporting text', max_length=30),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='hero_rotator_subtitle_font_size',
            field=models.CharField(blank=True, default='clamp(0.95rem, 1.4vw, 1.05rem)', help_text='CSS font size for rotating hero subtitles', max_length=30),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='hero_rotator_title_font_size',
            field=models.CharField(blank=True, default='clamp(1.25rem, 2.2vw, 1.75rem)', help_text='CSS font size for rotating hero text titles', max_length=30),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='hero_text_color',
            field=models.CharField(blank=True, default='#f5f7ff', help_text='Text color for hero intro and supporting copy', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='hero_title_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Text color for the hero title', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='hero_title_font_size',
            field=models.CharField(blank=True, default='clamp(2.5rem, 4.8vw, 4.3rem)', help_text='CSS font size for the hero title (e.g. 3rem or clamp(...))', max_length=30),
        ),
        migrations.AlterField(
            model_name='herobutton',
            name='url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='herotext',
            name='animation_type',
            field=models.CharField(choices=[('fade', 'Fade'), ('slide', 'Slide'), ('zoom', 'Zoom'), ('typing', 'Typing'), ('float', 'Float')], default='fade', help_text='Primary animation style', max_length=32),
        ),
    ]
