# Generated by Django 5.1.3 on 2026-07-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0022_herotext_animation_styles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='hero_content_animation_style',
            field=models.CharField(blank=True, choices=[('fade', 'Fade'), ('slide-up', 'Slide Up'), ('zoom', 'Zoom'), ('flip', 'Flip')], default='fade', help_text='Global animation style for hero content transitions', max_length=30),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='hero_eyebrow_animation_style',
            field=models.CharField(blank=True, choices=[('fade', 'Fade'), ('slide-up', 'Slide Up'), ('bounce', 'Bounce'), ('pulse', 'Pulse')], default='slide-up', help_text='Animation style for the hero eyebrow', max_length=30),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='hero_eyebrow_font_size',
            field=models.CharField(blank=True, default='clamp(0.8rem, 1.1vw, 0.95rem)', help_text='CSS font size for the hero eyebrow', max_length=30),
        ),
        migrations.AlterField(
            model_name='herotext',
            name='animation_styles',
            field=models.CharField(blank=True, default='fade,slide', help_text='Extra motion styles to rotate through, for example: fade, slide, typing', max_length=200),
        ),
        migrations.AlterField(
            model_name='herotext',
            name='animation_type',
            field=models.CharField(choices=[('fade', 'Fade'), ('slide', 'Slide'), ('zoom', 'Zoom'), ('typing', 'Typing'), ('float', 'Float')], default='fade', help_text='Main motion style', max_length=32),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='hero_animation_speed',
            field=models.PositiveIntegerField(blank=True, default=900, help_text='Animation speed in milliseconds for text transitions'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='hero_intro_font_size',
            field=models.CharField(blank=True, default='clamp(0.95rem, 1.35vw, 1.05rem)', help_text='CSS font size for the hero intro / supporting text', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='hero_overlay_opacity',
            field=models.PositiveSmallIntegerField(blank=True, default=50, help_text='Overlay opacity percentage (0-100)'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='hero_text_position',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', help_text='Position of hero text', max_length=10),
        ),
    ]
