# Generated by Django 5.1.3 on 2026-07-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0023_schoolsettings_hero_content_animation_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='hero_content_animation_style',
            field=models.CharField(blank=True, choices=[('fade', 'Fade'), ('slide-up', 'Slide Up'), ('slide-left', 'Slide Left'), ('slide-right', 'Slide Right'), ('zoom', 'Zoom In'), ('flip', 'Flip'), ('glow', 'Glow'), ('float', 'Float')], default='fade', help_text='Global animation style for hero content transitions', max_length=30),
        ),
    ]
