# Generated by Django 5.1.3 on 2026-09-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0027_backfill_default_tenant_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetheme',
            name='accent_color',
            field=models.CharField(default='#f59e0b', help_text='Accent color for buttons and highlights (hex format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='background_color',
            field=models.CharField(default='#f8fafc', help_text='Background color (hex format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='heading_text_color',
            field=models.CharField(default='#0f172a', help_text='Heading text color (hex format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='icon_color',
            field=models.CharField(default='#0f766e', help_text='Icon/emoji color (hex format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='icon_plate_color',
            field=models.CharField(default='#ccfbf1', help_text='Icon plate/background color (hex format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='primary_color',
            field=models.CharField(default='#0f766e', help_text='Primary color for header and accents (hex format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='secondary_color',
            field=models.CharField(default='#115e59', help_text='Secondary color for gradients (hex format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='text_color',
            field=models.CharField(default='#334155', help_text='Main text color (hex format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='accent_color',
            field=models.CharField(default='#f59e0b', help_text='Accent color for buttons and highlights (hex format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='background_color',
            field=models.CharField(default='#f8fafc', help_text='Background color (hex format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='heading_text_color',
            field=models.CharField(default='#0f172a', help_text='Heading text color (hex format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='hero_button_background_color',
            field=models.CharField(blank=True, default='#0f766e', help_text='Background color for hero CTA buttons', max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='hero_button_hover_text_color',
            field=models.CharField(blank=True, default='#0f766e', help_text='Hover text color for hero CTA buttons', max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='icon_color',
            field=models.CharField(default='#0f766e', help_text='Icon/emoji color (hex format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='icon_plate_color',
            field=models.CharField(default='#ccfbf1', help_text='Icon plate/background color (hex format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='primary_color',
            field=models.CharField(default='#0f766e', help_text='Primary color for header and accents (hex format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='secondary_color',
            field=models.CharField(default='#115e59', help_text='Secondary color for gradients (hex format)', max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='text_color',
            field=models.CharField(default='#334155', help_text='Main text color (hex format)', max_length=7),
        ),
    ]
