# Generated by Django 5.1.3 on 2026-09-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0028_alter_pagetheme_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='access_mode',
            field=models.CharField(choices=[('custom_domain', 'Custom domain or subdomain'), ('shared_path', 'Shared domain path')], default='custom_domain', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
