# Generated by Django 4.2.7 on 2026-01-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolClass',
            new_name='SchoolClasses',
        ),
    ]
