# Generated by Django 4.2.7 on 2026-04-19 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0005_make_required'),
        ('school_classes', '0002_rename_schoolclass_schoolclasses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_teachers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchemeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g., 2023/2024', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('objectives', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_schemes', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_classes.schoolclasses')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes_of_work', to='school_classes.teacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.term')),
            ],
            options={
                'unique_together': {('teacher', 'school_class', 'subject', 'term', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='TeacherPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view_students', 'View Students'), ('edit_students', 'Edit Student Information'), ('view_results', 'View Student Results'), ('edit_results', 'Edit Student Results'), ('print_results', 'Print Student Results'), ('print_broadsheet', 'Print Class Broadsheet'), ('view_attendance', 'View Attendance'), ('mark_attendance', 'Mark Attendance'), ('create_scheme', 'Create Scheme of Work'), ('edit_scheme', 'Edit Scheme of Work'), ('submit_scheme', 'Submit Scheme for Approval'), ('view_payroll', 'View Own Payroll'), ('view_payroll_dashboard', 'View Payroll Dashboard'), ('view_guardians', 'View Guardian Information'), ('contact_guardians', 'Contact Guardians')], max_length=50)),
                ('is_granted', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='school_classes.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='SchemeWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('topic', models.CharField(max_length=200)),
                ('sub_topics', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True)),
                ('teaching_methods', models.TextField(blank=True)),
                ('resources', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='school_classes.schemeofwork')),
            ],
            options={
                'ordering': ['week_number'],
                'unique_together': {('scheme', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_class_teacher', models.BooleanField(default=False, help_text='Whether this teacher is the main class teacher for this class')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school_classes.schoolclasses')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='exams.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='school_classes.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'school_class', 'subject')},
            },
        ),
    ]
