# Generated by Django 4.2.7 on 2026-04-30 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_classes', '0003_teacher_schemeofwork_teacherpermission_schemeweek_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeweek',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemeweek',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schemeweek',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemeweek',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scheme_weeks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schemeweek',
            name='is_acknowledged',
            field=models.BooleanField(default=False, help_text='Teacher reported completion for this week'),
        ),
        migrations.AddField(
            model_name='schemeweek',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin acknowledged the completion'),
        ),
    ]
