# Generated by Django 5.1.3 on 2026-08-31 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_classes', '0004_add_scheme_week_approval_fields'),
        ('settingsapp', '0025_tenant_schoolsettings_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclasses',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='settingsapp.tenant'),
        ),
        migrations.AlterField(
            model_name='schoolclasses',
            name='class_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='schoolclasses',
            unique_together={('tenant', 'class_name')},
        ),
    ]
