# Generated by Django 5.1.3 on 2026-09-01 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_alter_classsubject_unique_together_and_more'),
        ('school_classes', '0005_schoolclasses_tenant_alter_schoolclasses_class_name_and_more'),
        ('settingsapp', '0025_tenant_schoolsettings_tenant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classteacher',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='schemeofwork',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant'),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant'),
        ),
        migrations.AddField(
            model_name='schemeweek',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant'),
        ),
        migrations.AlterField(
            model_name='schoolclasses',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='classteacher',
            unique_together={('tenant', 'teacher', 'school_class', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='schemeofwork',
            unique_together={('tenant', 'teacher', 'school_class', 'subject', 'term', 'academic_year')},
        ),
    ]
