# Generated by Django 5.1.3 on 2026-09-02 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_classes', '0006_alter_classteacher_unique_together_and_more'),
        ('settingsapp', '0026_tenantmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='settingsapp.tenant'),
        ),
    ]
