# Generated by Django 5.1.3 on 2026-09-03 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_classes', '0007_teacher_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeofwork',
            name='completion_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='completion_admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='completion_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='completion_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='completion_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_scheme_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='completion_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='completion_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='reference',
            field=models.TextField(blank=True, help_text='Books, guides, websites, or other references used to prepare this scheme.'),
        ),
        migrations.AddField(
            model_name='schemeweek',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schemeweek',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
