# Generated by Django 4.2.7 on 2026-04-19 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_classes', '0003_teacher_schemeofwork_teacherpermission_schemeweek_and_more'),
        ('attendance', '0002_attendancerecord_marked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='school_classes.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('school_class', 'date')},
        ),
    ]
