# Generated by Django 4.2.7 on 2026-04-19 21:35

from django.db import migrations


def populate_school_class(apps, schema_editor):
    """Populate school_class field for existing attendance records"""
    AttendanceRecord = apps.get_model('attendance', 'AttendanceRecord')

    # Update existing records to use student's current class
    for record in AttendanceRecord.objects.filter(school_class__isnull=True):
        if record.student.student_class:
            record.school_class = record.student.student_class
            record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancesession_teacher_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_school_class),
    ]
