# Generated by Django 4.2.7 on 2026-04-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_populate_school_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='school_class',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, to='school_classes.schoolclasses'),
        ),
    ]
