# Generated by Django 4.2.7 on 2026-05-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_make_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="afternoon_present",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="morning_present",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="day_type",
            field=models.CharField(
                choices=[
                    ("school_day", "School Day"),
                    ("public_holiday", "Public Holiday"),
                    ("midterm_break", "Midterm Break"),
                    ("other", "Other"),
                ],
                default="school_day",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="week_number",
            field=models.PositiveSmallIntegerField(
                blank=True, editable=False, null=True
            ),
        ),
    ]
