# Generated by Django 5.1.3 on 2026-07-04 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancerecord_afternoon_present_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Christmas Holiday, Mid-term Break', max_length=100)),
                ('holiday_type', models.CharField(choices=[('public_holiday', 'Public Holiday'), ('school_break', 'School Break'), ('midterm_break', 'Midterm Break'), ('vacation', 'Vacation'), ('special_event', 'Special Event')], default='public_holiday', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Attendance Holidays',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_term_date_restriction', models.BooleanField(default=True, help_text='Restrict attendance marking to configured term dates')),
                ('allow_retroactive_marking', models.BooleanField(default=True, help_text='Allow marking attendance for past dates')),
                ('minimum_attendance_percentage', models.DecimalField(decimal_places=2, default=75.0, help_text='Minimum attendance percentage required (0-100%)', max_digits=5)),
                ('auto_mark_holidays_as_absent', models.BooleanField(default=False, help_text='Automatically mark students absent on holidays (if not explicitly marked)')),
                ('attendance_calculation_method', models.CharField(choices=[('days', 'By Days'), ('sessions', 'By Sessions (Morning/Afternoon)')], default='sessions', help_text='How to calculate attendance percentage', max_length=20)),
                ('send_low_attendance_alerts', models.BooleanField(default=True, help_text='Send notifications when student attendance drops below threshold')),
                ('school_has_morning_session', models.BooleanField(default=True)),
                ('school_has_afternoon_session', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Attendance Settings',
            },
        ),
    ]
