# Generated by Django 5.1.3 on 2026-09-01 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendancerecord_tenant_attendancesession_tenant'),
        ('settingsapp', '0025_tenant_schoolsettings_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceholiday',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='settingsapp.tenant'),
        ),
    ]
