# Generated by Django 5.1.3 on 2026-09-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendanceholiday_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesettings',
            name='afternoon_session_end',
            field=models.TimeField(default='15:00'),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='afternoon_session_start',
            field=models.TimeField(default='13:00'),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='morning_session_end',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='morning_session_start',
            field=models.TimeField(default='08:00'),
        ),
    ]
