from django.urls import path
from .views import (
    contact_view,
    contact_success,
    AdminMessageListView,
    AdminMessageDetailView,
    AdminPortalUserListView,
    AdminPortalThreadView,
    AdminPortalGroupsListView,
    AdminPortalGroupCreateView,
    AdminPortalGroupEditView,
    PortalInboxView,
    PortalThreadDetailView,
    portal_message_compose,
    send_portal_message_ajax,
    sync_portal_presence,
    fetch_portal_messages,
    fetch_portal_statuses,
    fetch_admin_portal_messages,
    fetch_admin_portal_statuses,
    start_class_thread,
    student_message_teacher,
)

urlpatterns = [
    path('contact/', contact_view, name='contact'),
    path('contact/success/', contact_success, name='contact_success'),

    path('admin/messages/', AdminMessageListView.as_view(), name='admin_messages_list'),
    path('admin/messages/<int:pk>/', AdminMessageDetailView.as_view(), name='admin_message_detail'),
    path('admin/messages/portal/', AdminPortalUserListView.as_view(), name='admin_portal_users_list'),
    path('admin/messages/portal/<int:user_id>/', AdminPortalThreadView.as_view(), name='admin_portal_thread_detail'),
    path('admin/messages/portal/thread/<int:thread_id>/', AdminPortalThreadView.as_view(), name='admin_portal_thread_detail'),
    path('admin/messages/portal/<int:user_id>/fetch/', fetch_admin_portal_messages, name='fetch_admin_portal_messages'),
    path('admin/messages/portal/thread/<int:thread_id>/fetch/', fetch_admin_portal_messages, name='fetch_admin_portal_messages'),
    path('admin/messages/portal/<int:user_id>/statuses/', fetch_admin_portal_statuses, name='fetch_admin_portal_statuses'),
    path('admin/messages/portal/thread/<int:thread_id>/statuses/', fetch_admin_portal_statuses, name='fetch_admin_portal_statuses'),
    path('admin/messages/portal/groups/', AdminPortalGroupsListView.as_view(), name='admin_portal_groups_list'),
    path('admin/messages/portal/groups/create/', AdminPortalGroupCreateView.as_view(), name='admin_portal_group_create'),
    path('admin/messages/portal/groups/<int:thread_id>/edit/', AdminPortalGroupEditView.as_view(), name='admin_portal_group_edit'),
    path('admin/messages/portal/class/<int:class_id>/start/', start_class_thread, name='start_class_thread'),
    path('portal/messages/student/<int:student_id>/message-teacher/', student_message_teacher, name='student_message_teacher'),

    path('portal/messages/', PortalInboxView.as_view(), name='portal_messages_list'),
    path('portal/messages/thread/', PortalThreadDetailView.as_view(), name='portal_thread_detail'),
    path('portal/messages/thread/send_ajax/', send_portal_message_ajax, name='send_portal_message_ajax'),
    path('portal/messages/thread/presence/', sync_portal_presence, name='sync_portal_presence'),
    path('portal/messages/thread/fetch/', fetch_portal_messages, name='fetch_portal_messages'),
    path('portal/messages/thread/statuses/', fetch_portal_statuses, name='fetch_portal_statuses'),
    path('portal/messages/compose/', portal_message_compose, name='portal_message_compose'),
]
